#!/bin/bash

echo "🔐 Google OAuth Redirect URI Setup"
echo "================================="
echo ""

echo "📋 Required Redirect URIs for Google OAuth:"
echo "========================================"
echo ""
echo "For Local Development (localhost:3001):"
echo "1. http://localhost:3001/api/auth/callback/google"
echo "2. http://localhost:3001/api/google/linking/callback"
echo ""
echo "For Production (replace with your domain):"
echo "1. https://yourdomain.com/api/auth/callback/google"
echo "2. https://yourdomain.com/api/google/linking/callback"
echo ""
echo "🔧 Google Cloud Console Setup Steps:"
echo "=================================="
echo "1. Go to: https://console.cloud.google.com/apis/credentials"
echo "2. Select your project or create a new one"
echo "3. Create OAuth 2.0 Client ID if not exists"
echo "4. In 'Authorized redirect URIs', add:"
echo "   - http://localhost:3001/api/auth/callback/google"
echo "   - http://localhost:3001/api/google/linking/callback"
echo "5. Copy the Client ID and Client Secret"
echo "6. Update your .env file with:"
echo "   GOOGLE_CLIENT_ID=your_client_id_here"
echo "   GOOGLE_CLIENT_SECRET=your_client_secret_here"
echo ""
echo "🎯 Microsoft OAuth Redirect URIs:"
echo "==============================="
echo "1. http://localhost:3001/api/auth/callback/microsoft"
echo "2. http://localhost:3001/api/outlook/linking/callback"
echo ""
echo "💡 Pro Tips:"
echo "============"
echo "- Use localhost:3001 consistently across all configurations"
echo "- Add both development and production URIs in Google Console"
echo "- Test OAuth flow after configuration"
echo "- Ensure HTTPS for production deployments"
